package com.laiba.wash.core.po;

import java.io.Serializable;
import java.util.Date;

public class UserOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.id
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.order_no
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.user_id
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.address_id
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.comment
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.mer_comment
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    private String merComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.money
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.status
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.create_time
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.update_time
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.transaction_id
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.out_trade_no
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.prepay_id
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    private String prepayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_order
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.id
     *
     * @return the value of user_order.id
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.id
     *
     * @param id the value for user_order.id
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.order_no
     *
     * @return the value of user_order.order_no
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.order_no
     *
     * @param orderNo the value for user_order.order_no
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.user_id
     *
     * @return the value of user_order.user_id
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.user_id
     *
     * @param userId the value for user_order.user_id
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.address_id
     *
     * @return the value of user_order.address_id
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.address_id
     *
     * @param addressId the value for user_order.address_id
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.comment
     *
     * @return the value of user_order.comment
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.comment
     *
     * @param comment the value for user_order.comment
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.mer_comment
     *
     * @return the value of user_order.mer_comment
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public String getMerComment() {
        return merComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.mer_comment
     *
     * @param merComment the value for user_order.mer_comment
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public void setMerComment(String merComment) {
        this.merComment = merComment == null ? null : merComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.money
     *
     * @return the value of user_order.money
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.money
     *
     * @param money the value for user_order.money
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.status
     *
     * @return the value of user_order.status
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.status
     *
     * @param status the value for user_order.status
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.create_time
     *
     * @return the value of user_order.create_time
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.create_time
     *
     * @param createTime the value for user_order.create_time
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.update_time
     *
     * @return the value of user_order.update_time
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.update_time
     *
     * @param updateTime the value for user_order.update_time
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.transaction_id
     *
     * @return the value of user_order.transaction_id
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.transaction_id
     *
     * @param transactionId the value for user_order.transaction_id
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.out_trade_no
     *
     * @return the value of user_order.out_trade_no
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.out_trade_no
     *
     * @param outTradeNo the value for user_order.out_trade_no
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.prepay_id
     *
     * @return the value of user_order.prepay_id
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public String getPrepayId() {
        return prepayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.prepay_id
     *
     * @param prepayId the value for user_order.prepay_id
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    public void setPrepayId(String prepayId) {
        this.prepayId = prepayId == null ? null : prepayId.trim();
    }
}