package com.laiba.wash.core.po;

import java.io.Serializable;
import java.util.Date;

public class WxAccessToken implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_access_token.id
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_access_token.access_token
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_access_token.start_time
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_access_token.end_time
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_access_token
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_access_token.id
     *
     * @return the value of wx_access_token.id
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_access_token.id
     *
     * @param id the value for wx_access_token.id
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_access_token.access_token
     *
     * @return the value of wx_access_token.access_token
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_access_token.access_token
     *
     * @param accessToken the value for wx_access_token.access_token
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_access_token.start_time
     *
     * @return the value of wx_access_token.start_time
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_access_token.start_time
     *
     * @param startTime the value for wx_access_token.start_time
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_access_token.end_time
     *
     * @return the value of wx_access_token.end_time
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_access_token.end_time
     *
     * @param endTime the value for wx_access_token.end_time
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}