package com.laiba.wash.core.dao.mapper;

import com.laiba.wash.core.po.UserOrder;
import com.laiba.wash.core.po.UserOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    int countByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    int deleteByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    int insert(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    int insertSelective(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    List<UserOrder> selectByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    UserOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserOrder record, @Param("example") UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    int updateByExample(@Param("record") UserOrder record, @Param("example") UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    int updateByPrimaryKeySelective(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Wed Sep 13 14:25:44 CST 2017
     */
    int updateByPrimaryKey(UserOrder record);
}