package com.laiba.wash.core.dao.mapper;

import com.laiba.wash.core.po.WxAccessToken;
import com.laiba.wash.core.po.WxAccessTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxAccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    int countByExample(WxAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    int deleteByExample(WxAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    int insert(WxAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    int insertSelective(WxAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    List<WxAccessToken> selectByExample(WxAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    WxAccessToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") WxAccessToken record, @Param("example") WxAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    int updateByExample(@Param("record") WxAccessToken record, @Param("example") WxAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    int updateByPrimaryKeySelective(WxAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Thu Aug 24 16:03:01 CST 2017
     */
    int updateByPrimaryKey(WxAccessToken record);
}